apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:YEIflW3uCF4IxcCH6ilOhQ2PsansYZuDxzPlphcFMq8+4Dkl+ICIEWU2E5xZIYKOUCOtGhgIcY/Bq//V4NQXOALPIQ/V6lo+67mD6g+qo1Mu2BPApmdouGZ6IIKEQ5bEeScjKJZuX/IVF8Q/nUh65yln63vthNJAGkvATlJClxNjFviGU15WVXeHCJFgRRBqHxXEz5WHf8vZE+Yob+YJtyydiDfAfYtHCHsyNQtX06iDSVAb/EFm4vzCvXVLuzHqBpnndGmJg2yOYmaWy0vfcyjvBaJUmqkReCCCeLMWI6ANkepjM5sRhiEud5H+yMG4TxSVIl/GKzpg4i/u0XSaUaWhqMWWZ6/31Q3cbGVrSUDVRVRSN0s5e5mDJTj/Ch0x,iv:Z0LFg2PQqLoIo5bVcQz5uw1xrYsynXxbj1qHAEjr7K8=,tag:BBPahmRsJNunhnPYRAXCYw==,type:str]
    identity.pub: ENC[AES256_GCM,data:Ye9pGwrBxZoKiUWfKH8oVdLlGJChjuatIcq9Jv0yENvy9dhYqy1kzbmaAPVDOz1VuEO7eXd/VJj8X75/rt6kBJ7wgTj7Lz6mUpVJhiGBsue7XLmhrtq5nJaTFSe6adZ0L+20t9uwZrcOrPtDsQrLxbAE/+BPdCU306DffjbSvFbmANoOR7dtZm+5k+B2nD0RTB8kjYJs87yKpkllfPD6olclVFL+Q0AkSCnNzDv3mHujwocOyEEJGBPZgBY1B3Q800nuCmA/ezGKVLF8Tg==,iv:1VRsFRdFliGfNlSMRqmq2NCQwbzLzN5tPk3EpCI2A3c=,tag:upzsI74aEoLyp21T8VWnGQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:tbG8fSadPhF5orSck4/eFUCIghCDKM9i5D9o2dQUwapr8O5qJqSeibNkvwDzcfZfwHfJM4mXl8YeEKWwdeqkA7/dI3A3M8/f4dp9yuY0lCQhBZGczQdM8ETeA9YYRYbf+qbczdpputckkMmv4/ybcuIQV5kKoYwkknc+kPjbzoXAok+nRc5NvRlXyFZOyrP4DCza1L8Q8Vx9O5U1yfiyNrBiaAT5XgTip3sf,iv:kFwsQIcYa9EORqML36cr2Mv7EKVFwUm0TGt3QlozRD4=,tag:G0rIaeZOxHobmqQQmci0Jw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1qf4nxu6mqqvlarzw42ep4xku632pgv28kt4gm2rrsaza2j70l3uqnhs2na
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2M3dQeW8zQitYQytPNjJL
            VTFkSXdpVDRhT3pBU0RaeXBEYW9xWFpsaVU0Ck9oTHZGY3Zhbk5pdzZlSlRHeGtp
            RE1sbzMwL3pzcThabEZQVnNMallwRHMKLS0tIFR2dS9GZWhTa0k4bnQvMXIyVmdN
            SjlCNFJMMDhpc3VyT1ptYTJlM3BtR2sKAeUPl9oS6q6F8olibDjHu6IjIArQG2+W
            W6rZrvgib3eZcnhhkYZOOnuPL8FmMxhvzIK68eQyOWJBFo3WrBNOVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-27T20:52:50Z"
    mac: ENC[AES256_GCM,data:Mm54+xgix8yX7YXjpEVl2yVduFNpN9JIcU7/HZgjtZUU6Zmng1hLwE5JhdjiMhvtprl5cGi5yv5WqJtN6/2w1UXbOTYQGCaVFvwL87h9xo8rRlTzZQYCMzDljleasSmYIKksbQleW7+YPCz5PGXt7OPEmSDgvCZhZlFzjgs9qNg=,iv:Rg4y4wZh2QKqBP0PySsEuwPPcwlbmrou9O7v4/YDqvo=,tag:lyjl/z1zrPAxjB5TvBGIJw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
