apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Ab2JJkRrOsZb32EhmJR0Y+LcRB9aEQUg735fJ+/LaLw+BzuOSICnKmXeYc6BUo4StWjFnBjX4vq45wKKAcx45+e0WHlmRulVm1YN0R7z5j6PavBAgXb0t3NwIsIMLshKF5BSnpV4GoV8b2n93R82irqLDcI709XJU9aBGR2VUwNNYefN83jEW2TkFFTDI9WInnRTJZhE5t8DaMZE6YjP/e1JF9EXsqM5mTlFgrYZ6f8XFse0gf2QDbPcxdP2Po6dk/TG0AFUbkJcJzWkn7kwnW6ziCWFkhtrBVbx2hSMmibcFWY9zZ9WX0IGED8xquYdmgNashEXKH3mvr0TmbWaHfQk8uRYoeUQf4jdh9kHyMw7xUbM1MwyBfr9KxYeqgt6,iv:iKKMzjKpljjNiIRrOACtviK+NEDrbDHJP4NEufGCx+8=,tag:zywD6tGU0XWwAQjhia71iQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:3QZxvY/QmVWqEaTbUEUvRY/TMEnCQMJNkNW/PPxavI3thxR56pWCAz503YDjENrrI7yjF9O2ncqR5IVnGHxWx/a9i0HvaU4z/XYgUW9XIIN3bjIdZaqUBrahxHruFRmidqz77clpduG04OttmIfcQ5y3RyaSEjrmpV+O0a0GX2lIH3Uw8Sax4buYZ12HIYC0TL2luELEvl6HYxLTqH4Kf5nS332dZkJNB9yYRBqWby6PsVgNP7Nz+QH4omTxo2SqsNtzEcG/tTDiFThbEw==,iv:PcyfqoNtYTuYiM974ZCVa5IZXi2oRST8dv5tsbLnUTA=,tag:GCgmYgIOG9yG7wc4lVWslQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:Ttfni3TeFDBOGUprWwHWXudW2fvVLZ1x9hYvxn0CtbxCpAemB6n6zzUXxHjZR6t1perQ7WLC2yJ0joIrR07u0cE2Zzlt+SUP3rK6hu4a/oB7qaqg9YlUsTd5z+1tIdCvnBXl2iLDqWHOcxZKJktXFEnAhc/lbuqsEdtzUwV+RNNGnOb+1u4iLuzLhOHsq9H+GElpLNYxggKwEfHGKiaAUKUUBJeFvo94U5Lb,iv:GCm8qnkamY12jCQNXgVQ0sI+j1OuMt2q21yDAPUfNgQ=,tag:8ChXRa/LgfT+Vs6zpRhLmg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1qf4nxu6mqqvlarzw42ep4xku632pgv28kt4gm2rrsaza2j70l3uqnhs2na
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzL0RZbGZ0U0c1bXk0UU9k
            RHRBK1ZFN3IrV2VleFJIRDVLMElsdzBQQ0F3CjhJaEpSbzlxZXhGdVU3UEY3RVBV
            R0NPOGdLLzZKOEFHU1R4VWhLSFhqd0kKLS0tICtYM2NXR2dkaStUOXpNU2lEa2pU
            cFVveHdFRmpvb0hPK3llNGhndjFZQWMKPT2lx+qwJ6LkmoaBTYstBVWFSKbZEKjB
            CZqhvBDWlKaHnC+gDW5PZTqpnSu+kDkdFdszfX2+LLW3qsJ0PiwsJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-02T14:46:12Z"
    mac: ENC[AES256_GCM,data:8BnFx3VX0kTHdyrWiiYpT7fV4oNzuzsqV21o5cOeYZrjNSIUoRVmiPzx4C6PmZaXIffEmd5tFs5sjT/3dSz76MPOfTpDO6m5LDh/xUHZrE73LMGpZw4njlMYwEXXJxlYSsWHIeOLrleZYOp6jWrM/QLNDs3DiUu65XLfKWz/wRo=,iv:IrnUdQgNswELOfx9dAfXdhxDqsptUzgsgNj/Wc4EhLc=,tag:GzqW5QOrOW07J6wtnoqy2Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
