apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ub+nICfXzWh1372tSMZFvVoWRk5ANHUQtJaFjQHYLYzdIkyhh/69zh+1StIXmr/E3trug3NgRKGUTx4ZbvAY+w8O77un5ylleqoqebeOxlHHC0cxaA+Z1pqKcKPSFbniL85NbaFxWScTYLoS54GbLqMJZNFhSNBrseRW95uMUTOOHVKuFGjBiz5j/wmhpdJyZgPhOfOUIl2FPK1fgGcRv7EmgKIQHpUrwxxwozLidnK9gH4HZ2o+acGgTPqQtrh0BXG2EMvhB7QEaxX0gRinj8uqoe+eO0wTJZadtjJWrfw7H20n1XppCLStL6lghvtLAk6ziLETnm2KaAU9+7xDu/JE9hxcy2RRmxVVGfO/hMSKXrDp9hOd0CEvKQWvMfgL,iv:Nu42XQ9JhWJ0xMskV5FClX8+OcgwUNwmQyv/gnV9CV0=,tag:fnORUAZu6CSGmN6u2Ctymg==,type:str]
    identity.pub: ENC[AES256_GCM,data:DlJTG1afLQn1mc50KypKZhTGSn2nC2Fcw9JVMVzzhYuzPhMrft36R3K6qxM9cBfn0SCaQCUVgDadDYQ/v+thrcgl+evbZGXn1rNPE9HH3ZbuPTQC5Wwp+HSYnVeiCALSp8tQmJUKElOxVp57g3LhzHPoWgH9AJacoFTTvYWkochMthJzXh4mzC702uz4bzFZJEvdsKJITjca/YDFE2hBTLqLeCdriU0SU5WP1DFdz5AEwip+x3YPwRo7FiJ04UhRAhd+8WsKDdzyc2luyg==,iv:rLK0imFbDPzHZb6hvxiySiXoWUX01ds1RSxez8aKB6o=,tag:QePjgzLRpEEutCr/XtFSnA==,type:str]
    known_hosts: ENC[AES256_GCM,data:xRz1vH2UWhct+ScshpxRmNOzca7lDJL7HhZvVbP161uGA0113PPjaKlX4l0SdpeBB9rHVNL0J4odkw7vC7I2ySxo8z925Sp5e4r0+G+AKP5GbZgc9NZlgvvSbNqgA1LdTtfSQKc94whVStEI2kPM60BSGS/vOPbKEUvocx/T/OKj5N7x4I/2Aw1d1jjCyjbAT/TrzkhzhDz23WzZfcEK9uJWIqwyAjiTDh+0,iv:E9d3kr7fRqc6vgQesOsaygdGq54v/VBfsso0UX2ShP4=,tag:5KQ0RaPPoxqu9bAtY8lfmg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1qf4nxu6mqqvlarzw42ep4xku632pgv28kt4gm2rrsaza2j70l3uqnhs2na
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwRWJxQXhUTm8vN1dpQVVG
            anUwUzRSR25IcWRVZXUwNTVzVXNQRHNocFhBCnVwVmN3dTJYK2RoRHVTV2NTcWJm
            b3VVWTVBZXFteWhIZVkwWnRGUTBxUGMKLS0tIGZTNGNwSEt4YUhIbnZlZlNvdENY
            S0xMZjBNS3E5bVk5djFtN1gwSC9wbXcKVohtmXMViMifR7qtdtKiwgzuAHkLF2OV
            lsw2qcOJgYdUtCWRWQui/JM9CcJrgRTIqVYkw+XZsNhpQ4mBR9a4fQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-02T15:07:05Z"
    mac: ENC[AES256_GCM,data:596d54OkjmgRHTlMALu1LZsGPfQQEhYGkKq2LYbRKAMl9b5+nJBbzZm15qnj9Jc/BcjOmK8TYG4WNUepnqAGw+AA+eMQfWPs7FSUGnjgcQgLeUCe7u3+dUwUoC5ioNrbVcLrew6u+JA8QUrOHjw0VjPH2dMghS7LWA1InUpcmK0=,iv:RkKA2Rb///m06Uq7pLXmwlF5u9rJMUAma9hfTOR5kAI=,tag:kFhj2U03u3nfmbXfEIEndQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
